### PR TITLE
Do not warn about colors in lists in variables

### LINKED ISSUE #936: ColorVariable incorrectly warns on colors in lists
If I were to define a list, like a shadow:

```scss
$my-shadow: 2px 2px 2px rgba(0, 0, 0, 0.2);
$my-other-shadow: 2px 2px 2px #f00;
```

I currently get a ColorVariable warning for each line. ☹️

### PR DESCRIPTION
**Pull request by srawlins**
Fixes #936

### CODE REVIEW

File: lib/scss_lint/linter/color_variable.rb [hunk 1]
```diff
@@ -55,11 +55,13 @@ def literal_string?(script_string)
     def in_variable_declaration?(node)
       parent = node.node_parent
       parent.is_a?(Sass::Script::Tree::Literal) &&
-        parent.node_parent.is_a?(Sass::Tree::VariableNode)
+        (parent.node_parent.is_a?(Sass::Tree::VariableNode) ||
+         parent.node_parent.node_parent.is_a?(Sass::Tree::VariableNode))
```
Comment (srawlins) [inline lib/scss_lint/linter/color_variable.rb]: I didn't see any guards elsewhere in this file for `parent_node` being nil. Should we sprinkle in some nil checks?

Comment (sds) [reply lib/scss_lint/linter/color_variable.rb]: There will always be a parent (at the very least, a `Sass::Tree::RootNode`).
